spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.google.com/
          predicates:
            - Query=url, google

        - id: ins_route
          uri: https://www.instagram.com/
          predicates:
            - Query=url, instagram

        # 精确路由放在高优先级
        - id: third_party_route
          uri: lb://novabazaar-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: product_route
          uri: lb://novabazaar-products
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}



# 前端项目，/api
# http://ocathost:88/api/captcha.jpg -> http://localhost:8080/renren-fast/captcha.jpg
# http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/List/tree